# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20b8c8f078cec7631933a87e355a1600a7d6b99995ed7ec63173fbc7d195b029b5395e70d9d65832116725c6ab1965380b918e5d916456b484902770b2e36131

test:
  secret_key_base: afe3f70e81a53a1a7136a5b1df993b0958ca869e85fbf8bb5bef6a1df3ed76b2d59f3bf38bae2fe95611d5e83a71b171fb4324166ae208b16e67b97c538e68ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
